#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("quizapp.Droid.Resource", IsApplication=true)]

namespace quizapp.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int about = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int appicon = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int appiconWhite = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int back = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int category = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int circleda = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int circledq = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int help = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int picture = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int questionmark = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int quiz = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int quizbackground = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int quizbackgroundv2 = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int randomquestions = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int settings = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int trophy = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int vicon = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int xamarin_logo = 2130837521;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int sliding_tabs = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int toolbar = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Tabbar = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Toolbar = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int icon = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int icon_round = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int launcher_foreground = 2131034114;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7F060000
			public const int categorystats = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int playerstats = 2131099649;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int AppCompatDialogStyle = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int MainTheme = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int MainTheme_Base = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
